import { build } from "esbuild";
import { spawnSync } from "node:child_process";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
const require = createRequire(import.meta.url);
const output = fileURLToPath(new URL("../../../.desktop-build-temp/browser-controller.cjs", import.meta.url));
await build({ entryPoints: [fileURLToPath(new URL("../main/browser-controller.ts", import.meta.url))], outfile: output, bundle: true, platform: "node", format: "cjs", external: ["electron"], target: "node24" });
await build({ entryPoints: [fileURLToPath(new URL("../../../src/web-search.ts", import.meta.url))], outfile: fileURLToPath(new URL("../../../.desktop-build-temp/browser-policy.mjs", import.meta.url)), bundle: true, platform: "node", format: "esm", target: "node24", banner: { js: 'import {createRequire} from "node:module"; const require=createRequire(import.meta.url);' } });
const result = spawnSync(require("electron"), [fileURLToPath(new URL("browser-smoke-harness.cjs", import.meta.url)), output], { stdio: "inherit", windowsHide: true, timeout: 45000 });
if (result.error) throw result.error;
process.exit(result.status ?? 1);
