export const desktopTerminalVisuals = {
  minimumContrastRatio: 7,
  cursorStyle: "bar" as const,
  cursorInactiveStyle: "outline" as const,
  theme: {
    background: "#111827",
    foreground: "#e5edf7",
    cursor: "#f8fafc",
    cursorAccent: "#111827",
    selectionBackground: "#31547f",
    black: "#a3b2c7",
    red: "#f87171",
    green: "#4ade80",
    yellow: "#facc15",
    blue: "#60a5fa",
    magenta: "#c084fc",
    cyan: "#22d3ee",
    white: "#e5edf7",
    brightBlack: "#cbd5e1",
    brightRed: "#fca5a5",
    brightGreen: "#86efac",
    brightYellow: "#fde047",
    brightBlue: "#93c5fd",
    brightMagenta: "#d8b4fe",
    brightCyan: "#67e8f9",
    brightWhite: "#ffffff",
  },
};
